### ISSUE TITLE
Update the tagline text on the Browse Events page

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#30]
![image](https://user-images.githubusercontent.com/39232022/113462425-63a6bc00-9453-11eb-834e-40db307434d6.png)
The tagline text on the Browse events page currently says "Competition and others" (refer to screenshot) and can be improved.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/BrowseEvents.vue`
3. Find the line that says "Competition and others" .
4. Replace it with "Competitions and more" or something better.
5. Follow the steps to submit your PR.

**Comment by multipletwigs** [comment]
Hi I want to contribute - Julian's group

**Comment by julkhong** [comment]
my mentee Zach has done this issue
