### ISSUE TITLE
Update an option in the UserMenu 

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#31]
![image](https://user-images.githubusercontent.com/39232022/113462567-1e36be80-9454-11eb-8a71-f335b0a9af04.png)
There is a menu that is displayed when you click on your name in the top-right corner of the platform. The first option says "User Info" (refer to the screenshot) and can be improved.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/modules/navigation/UserMenu.vue`
3. Find the line that contains "User Info" and replace it with "User Profile".
4. Follow the steps to submit your PR.

**Comment by sjoyee** [comment]
I'm working on this.
