### ISSUE TITLE
Increase padding for the Button 

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#32]
Your task is very simple - just increase the padding for the Button component.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/common/styles/_variables.scss`
3. Find the line that says `$btn-padding: 5px 40px;` 
4. Change the padding to `8px 45px` or something better.
5. Follow the steps to submit your PR.

**Comment by MrAbhishekShrestha** [comment]
I want to contribute - Team Blaise

**Comment by sushii2001** [comment]
hii, me and Zoe from Min Hao group would like to  contribute this issue
