### ISSUE TITLE
Remove underline from footer links

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#33]
![image](https://user-images.githubusercontent.com/39232022/113463176-f72dbc00-9456-11eb-824c-ba816bda1317.png)
As per the screenshot, there are two links in the footer of the home page that has an underline. We need to remove this.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file `src/views/Home.vue`
3. Find the lines that display the "Privacy" & "Terms & Conditions".
4. You will notice they both have the `<u>...</u>` tag. You need to remove these tags.
5. Follow the steps to submit your PR.

**Comment by gohxiean** [comment]
Im doing this, please assign me. Thanks :)

**Comment by NitinMa2** [comment]
Will do @gohxiean . Ask your pair to comment also please

**Comment by carrotan30** [comment]
I'm pairing up with Xie An

**Comment by carrotan30** [comment]
We submitted a pull request on the issue. It is under @gohxiean 's name. ^^
