### ISSUE TITLE
Add a left and right margin to the event and profile cards

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#34]
There is currently no margin and the profile cards sometimes touch edge to edge without any space in between. Refer to the screenshot to see the issue.
![image](https://user-images.githubusercontent.com/39232022/113463301-a66a9300-9457-11eb-80a7-be93690684ca.png)

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file `src/modules/main/ProfileCard.vue`
3. We need to modify the css so scroll down still you see the <style> tag around line 110.
4. Under the `profile-card` class, we need to add the following lines:
```css
margin-left: 5px;
margin-right: 5px;
```
5. Follow the steps to submit your PR.

**Comment by HeyItsSean8** [comment]
Hi, can I try out this issue, thanks.

**Comment by NitinMa2** [comment]
Hi @UnknownSean8  thanks for taking up this issue. I'll review the PR and add my comments there

**Comment by UnknownSean8** [comment]
Hi @NitinMa2, I edited the commit and submitted a new PR. Thanks.

**Comment by NitinMa2** [comment]
Closing this PR! Thanks @UnknownSean8
