### ISSUE TITLE
404 page UI update

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#35]
![image](https://user-images.githubusercontent.com/39232022/113464182-5db5d880-945d-11eb-86dd-1951786f9f98.png)

If you enter some random address on the Eureka site, it displays the 404 page as in the screenshot. Do you have any ideas to make this page better? Get creative - you can update the illustration and/or the text.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/NotFound.vue`
3. Edit the relevant content.
4. Follow the steps to submit your PR.

**Comment by samwzlim** [comment]
I'll be doing this

**Comment by Zoe-0614** [comment]
hii, me and Zhen Kang from Min Hao group would like to contribute this issue

**Comment by Zoe-0614** [comment]
Hi, I have contributed in this issue thanks

**Comment by julkhong** [comment]
There will be a conflict where multiple participants took up this task, please take note team
