### ISSUE TITLE
Add a few interest topics

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#36]
(Multiple contributors can take up this task)
![image](https://user-images.githubusercontent.com/39232022/113464346-6824a200-945e-11eb-8fce-58f7ba397817.png)

On the User Profile page, there is an option to select interests. These are hard-coded values. Do you think there are any interests missing and you would like to add? Your task would be to add relevant tech interests. Things like 'Open Source', 'Kafka', 'Hadoop', etc. can be added.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/UserProfile.vue
3. Find the array variable `interestMenu`.
4. Modify it and add the new options.
5. Follow the steps to submit your PR.

**Comment by gohxiean** [comment]
Please assign me and Caleb Tan (carrotan30) to this, thank you :)

**Comment by carrotan30** [comment]
Yes, thank you!

**Comment by julkhong** [comment]
Done by my mentees
