### ISSUE TITLE
Rename the feedback form subject options

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#37]
![image](https://user-images.githubusercontent.com/39232022/113464529-ea619600-945f-11eb-82bd-0bac19763836.png)

When you go to the feedback page and select a subject, there are 3 default options. These need to be renamed.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/Feedback.vue`
3. On line 13, there will be a list of options which you need to modify. Change it to:
```js
 :options="{
        suggestion: 'Suggestion', 
        bug: 'Something's not quite right', 
        compliment: 'Compliment'
    }"
```
4. Follow the steps to submit your PR.

**Comment by SauceFoong** [comment]
Team Blaise pciked

**Comment by NitinMa2** [comment]
Alright! Let your pair also comment and I'll assign you both

**Comment by SauceFoong** [comment]
> Alright! Let your pair also comment and I'll assign you both
Sorry, this is done individually without pair /.\
