### ISSUE TITLE
Create an "Under Maintenance" page

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#40]
Knowledge of HTML & CSS is required. Your task is to design and develop a page to use when the site is under maintainence. You can duplicate the 404 page to use as a template.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Duplicate the file, `src/views/NotFound.vue`
3. Rename the file & modify the code
4. Follow the steps to submit your PR.

**Comment by Jason-Toh** [comment]
I'm taking this issue

**Comment by Fo00zi** [comment]
im taking issue with jason

**Comment by NitinMa2** [comment]
Alright, I've assigned the both of you
