### ISSUE TITLE
Update the error messages

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#41]
(This task can be handled by multiple contributors)

![image](https://user-images.githubusercontent.com/39232022/113468427-b9418f80-9478-11eb-856c-8029c5393559.png)

We are using a plugin called sweetalert2 to handle the pop-up error messages that are displayed when something goes wrong. You can try to submit feedback form with a body but no subject to see how the popup works. Your task is to update the text displayed in the error messages. There is nothing wrong with them now but here's your chance to get creative and use more flowery language or have a play with words.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Use global search to find "`Swal.fire({`" and that will point to all the places where the alert was called.
3. Navigate to the files, understand what the error is and improve the error message.
4. Follow the steps to submit your PR.

**Comment by AugustDespair** [comment]
Mikey and I under Min Hao want to handle this issue.
