### ISSUE TITLE
Change the user cursor to pointer when user hovers on the wave button

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#42]
![image](https://user-images.githubusercontent.com/39232022/113468545-556b9680-9479-11eb-943e-2ca5f511c5ff.png)

On the talent and mentor pages, when we want to wave at someone, hovering over the wave icon should change the cursor to a pointer.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/modules/main/ProfileCard.vue`
3. Find the div that has the class "profile-card__wave".
4. Add "cursor__pointer" to the class.
5. Follow the steps to submit your PR.

**Comment by mltw** [comment]
I'm working on this, thanks
