### ISSUE TITLE
Remove the arrow icon in login page and sign up page

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#44]
![image](https://user-images.githubusercontent.com/39232022/113468751-bd6eac80-947a-11eb-85a9-3e01c853a7ea.png)
![image](https://user-images.githubusercontent.com/39232022/113468759-c52e5100-947a-11eb-8510-66ead503d09c.png)

There is an arrow icon that appears on some devices and displays as a crossed box on others. Let's either remove it or replace it with a proper icon using Google Material Icons.

Documentation for Google Material Icons - https://google.github.io/material-design-icons/
Note that all the necessary setup and imports are done. You would just need to add the line of code that displays the icon.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/Login.vue`
3. Find the line that says "Create a new account &#11166;". 
4. "&#11166;" is what is used to display the arrow this needs to be dealt with.
5. Repeat th same for `src/views/Signup.vue`.
6. Follow the steps to submit your PR.

**Comment by DineshKoushik** [comment]
@NitinMa2 , Hey I'll give this a try

**Comment by NitinMa2** [comment]
Hi @DineshKoushik kindly hold on while we still set up. There is a possibility this task won't be assigned to you yet. We are reserving these tasks for a specific purpose. More later.. cheers
