### ISSUE TITLE
Show no mentors found when no mentors after filter

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#49]
Knowledge of conditional rendering is required.

![image](https://user-images.githubusercontent.com/39232022/113469580-3244e500-9481-11eb-8b7a-5d26365bdcd1.png)

On the mentor page, when you enter multiple filters and there is no mentor to display, we want to show some text instead of leaving the screen blank. This improves the UX of the platform.

Steps to accomplish the task:
1, If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/FindMentor.vue`
3. The array variable `filteredMentors` is used to display the mentors. If the length of this array is 0, display some placeholder text instead. You can decide on what to display.
4. Follow the steps to submit your PR.

**Comment by SauceFoong** [comment]
Done, this is the pull request for it. 

[Show no mentors found when no mentors after filter #77]
