### ISSUE TITLE
Add validation to the user profile bio input field

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#50]
When you go to the User Profile and try to update your bio, there is no limit on how many characters you can type. Your task would be to set a reasonable limit (say about 200 characters).

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/UserProfile.vue`
3. Find the input tag that has the id `bio`.
4. Manipulate the Javascript to limit the character count.
5. Follow the steps to submit your PR.

**Comment by Theger14** [comment]
I'm working on this.

**Comment by NitinMa2** [comment]
Alright, I will assign you @Theger14  can you ask your pair to comment as well?

**Comment by Diesel-Hadez** [comment]
Hi I am the paired person. One thing I want to add is that the current solution is very simple, and has room for improvement. For example, an error message telling the user that the max character length is 400 could be used, instead of simply giving an error without any message as to the why.

**Comment by Theger14** [comment]
> Hi I am the paired person. One thing I want to add is that the current solution is very simple, and has room for improvement. For example, an error message telling the user that the max character length is 400 could be used, instead of simply giving an error without any message as to the why.

I have addressed the issue above by extracting the validation code into a new function.

**Comment by NitinMa2** [comment]
Thanks for the improvement @Theger14 ! It certainly impacts the UX positively and a future improvements could include displaying the character count live.
