### ISSUE TITLE
Change the user profile bio input field to a textarea

### ISSUE THREAD

**Issue by NitinMa2** [MUM-Open-Source/eureka-web-app#51]
When you go to the User Profile and try to update your bio, there is an input tag used. But a bio is descriptive so it would make more sense to use a textarea. We already have a textarea implemented for the feedback form. Your task would be to change the input field to a textarea.

Steps to accomplish the task:
1. If you haven't done already, create a new branch that you'll make your changes on.
2. Navigate to the file, `src/views/UserProfile.vue`
3. Find the input tag that has the id `bio`. This is what needs to be replaced.
4. Navigate to the file, `src/views/Feedback.vue`
5. Find the textarea tag that has the id `feedback__message`. This is what you need to replicate. Don't forget to include the styles.
6. Follow the steps to submit your PR.

**Comment by mgs-mnlngt** [comment]
I've attempted this issue.

**Comment by NitinMa2** [comment]
Alright, I've assigned you
